ГАЙД ПО NUMPY ОТ ДАНИ АНИКИНА

In [2]:
import numpy as np

СОЗДАНИЕ МАССИВА (МАТРИЦЫ)

dtype - определяет сколько бит потратить на числа (по дефолту == 32)

In [3]:
ar = np.array([1, 2, 3], dtype='int32')
ar

array([1, 2, 3])

многомерные массивы

n-мерный массив состоит из какого то числа (n-1)-мерных массивов 

In [4]:
matr = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]], dtype='int8')
matr

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]], dtype=int8)

узнать количество измерений массива 

In [5]:
matr.ndim

2

посчитать количество строк и столбцов

In [6]:
matr.shape

(4, 3)

узнать тип массива 

In [7]:
matr.dtype

dtype('int8')

узнать количество элементов в массиве

In [8]:
matr.size

12

ДОСТУП К ЭЕЛЕМЕНТАМ

название_массива[элемент_1_уровня, элемент_2_уровня ... , элемент_n_уровня]

In [9]:
matr[1, 2]

2

также мы можем присвоить значение элементу

In [10]:
matr[1, 2] = 12
matr[1, 2]

12

оператор : позволяет выбрать все элементы выбранного уровня 

выберу нулевой элемент каждый строки

In [11]:
matr[:, 0]

array([1, 2, 3, 4], dtype=int8)

выберу все элементы нулевой строки

In [12]:
matr[0, :]

array([1, 1, 1], dtype=int8)

In [13]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

срезы и длина шага

In [14]:
a[0, 0:4:2]

array([1, 3])

создать матрицу с нуями

In [15]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

создать матрицу с единицами

In [16]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

создать матрицу заполненную произвольными числами

In [17]:
m = np.full((2, 3), 5)
m

array([[5, 5, 5],
       [5, 5, 5]])

создать матрицу рандомных чисел

In [18]:
rand = np.random.randint(-10, 10, size=(5, 4))
rand

array([[  4,   1,   8,  -1],
       [  9,  -3,   6,  -6],
       [  3,   5,  -7, -10],
       [ -7,   2,   0,  -9],
       [ -7,  -5,  -2, -10]])

создать единичную матрицу

In [19]:
ed = np.identity(4)
ed

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

МАТЕМАТИЧЕСКИЕ ОПЕРАЦИИ

In [20]:
a = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
b = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])
c = np.array([1, 2, 3])

In [21]:
b -= 2
b

array([[-1,  0,  1],
       [ 0,  2,  4],
       [ 1,  4,  7]])

In [22]:
a + b

array([[ 0,  2,  4],
       [ 2,  6, 10],
       [ 4, 10, 16]])

In [23]:
a * b

array([[-1,  0,  3],
       [ 0,  8, 24],
       [ 3, 24, 63]])

In [24]:
a / b

C:\Users\foksm\AppData\Local\Temp\ipykernel_13304\1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([[-1.        ,         inf,  3.        ],
       [        inf,  2.        ,  1.5       ],
       [ 3.        ,  1.5       ,  1.28571429]])

матричное умножение 

In [25]:
a @ b

array([[ 2, 16, 30],
       [ 4, 32, 60],
       [ 6, 48, 90]])

АГРЕГАТНЫЕ ФУНКЦИИ

у агрегатных функций есть параметр axis, он определяет по какой оси будут производиться вычисления

Axis 0 - по первой (вертикаль)

Axis 1 - вторая (горизонталь)

In [28]:
matr

array([[ 1,  1,  1],
       [ 2,  2, 12],
       [ 3,  3,  3],
       [ 4,  4,  4]], dtype=int8)

In [27]:
matr.sum(axis=0)

array([10, 10, 20])

In [29]:
matr.sum(axis=1)

array([ 3, 16,  9, 12])

ТАК ВОТ, АГРЕГАТНЫЕ ФУНКЦИИ

сумма элементов

In [30]:
matr.sum()

40

среднее значение

In [31]:
matr.mean()

3.3333333333333335

минимальное и максимальное значения

In [32]:
matr.min()

1

In [33]:
matr.max()

12

произведение элементов

In [34]:
matr.prod()

82944

дисперсия

In [35]:
matr.var()

8.055555555555555

стандартное отклонение

In [36]:
matr.std()

2.8382310609877335

КОПИРОВАНИЕ И ОРГАНИЗАЦИЯ

если присвоить значение массива a = b, то создастся ссылка на массив, и при изменении одного, будет меняться и второй

так что, используем функцию copy для создания нового массива

In [39]:
experemental = matr.copy()
experemental

array([[ 1,  1,  1],
       [ 2,  2, 12],
       [ 3,  3,  3],
       [ 4,  4,  4]], dtype=int8)

можно менять размер и форму массива

In [47]:
experemental.reshape((12, 1))

array([[ 1],
       [ 1],
       [ 1],
       [ 2],
       [ 2],
       [12],
       [ 3],
       [ 3],
       [ 3],
       [ 4],
       [ 4],
       [ 4]], dtype=int8)

In [49]:
np.resize(experemental, (2, 3))

array([[ 1,  1,  1],
       [ 2,  2, 12]], dtype=int8)